name: Unit Tests
run-name: ${{ github.actor }} is running unit tests
on: workflow_dispatch
jobs:
    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies and run Jest/RTL tests
              run: |
                  npm install
                  npm run test:coverage
